@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "PatientManager Storage" #F4F6F6{
Class "<<interface>>\nPatientManagerStorage" as PatientManagerStorage
Class JsonPatientManagerStorage
Class JsonSerializablePatientManager
Class JsonAdaptedPatient
Class JsonAdaptedPatientData
}

package "Appointment Storage" #F4F6F6{
Class "<<interface>>\nAppointmentStorage" as AppointmentStorage
Class JsonAppointmentStorage
Class JsonSerializableAppointmentManager
Class JsonAdaptedAppointment
Class JsonAdaptedAppointmentData
}

package "Keyword Storage" #F4F6F6{
Class "<<interface>>\nKeywordStorage" as KeywordStorage
Class JsonKeywordStorage
Class JsonAdaptedKeyword
}

package "VaxType Storage" #F4F6F6{
Class "<<interface>>\nVaxTypeStorage" as VaxTypeStorage
Class JsonVaxTypeStorage
Class JsonAdaptedVaxType
Class JsonAdaptedVaxRequirement
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" PatientManagerStorage
StorageManager -up-> "1" AppointmentStorage
StorageManager -up-> "1" KeywordStorage
StorageManager -up-> "1" VaxTypeStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> PatientManagerStorage
Storage -down-|> AppointmentStorage
Storage -down-|> KeywordStorage
Storage -down-|> VaxTypeStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonPatientManagerStorage .up.|> PatientManagerStorage
JsonAppointmentStorage .up.|> AppointmentStorage
JsonKeywordStorage .up.|> KeywordStorage
JsonVaxTypeStorage .up.|> VaxTypeStorage

JsonPatientManagerStorage ..> JsonSerializablePatientManager
JsonSerializablePatientManager --> "*" JsonAdaptedPatient
JsonAdaptedPatient --> "*" JsonAdaptedPatientData

JsonAppointmentStorage ..> JsonSerializableAppointmentManager
JsonSerializableAppointmentManager --> "*" JsonAdaptedAppointment
JsonAdaptedAppointment --> "*" JsonAdaptedAppointmentData

JsonKeywordStorage ..> JsonAdaptedKeyword

JsonVaxTypeStorage ..> JsonAdaptedVaxType
JsonVaxTypeStorage ..> JsonAdaptedVaxRequirement

@enduml
